# Generated by Django 3.1.4 on 2021-01-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
