# Generated by Django 3.1.4 on 2021-01-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210111_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='content',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
