# Generated by Django 3.1.5 on 2022-06-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220201_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='test', max_length=500),
            preserve_default=False,
        ),
    ]
