# Generated by Django 3.1.4 on 2021-01-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210112_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='content',
            field=models.TextField(default='Click to start typing', max_length=2000, null=True),
        ),
    ]
