# Generated by Django 3.1.4 on 2021-01-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210114_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='content',
            field=models.TextField(default='Click to start typing', max_length=5000, null=True),
        ),
    ]
