# Generated by Django 3.1.7 on 2021-04-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blog_post_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
